ANNOUNCEMENTS = [
    {
        "text": {
            "en": "URGENT: King Fahd Causeway reduced to one lane tonight 22:00–05:00 for barrier repairs. Expect delays.",
            "ar": "عاجل: تقليص مسارات طريق الملك فهد إلى مسار واحد الليلة من 22:00 إلى 05:00 لأعمال صيانة الحواجز. توقعوا تأخيرات.",
        },
        "severity": "urgent",
        "active": True,
    },
    {
        "text": {
            "en": "Dense fog advisory for northern highways until 09:00. Reduce speed, use fog lights, double following distance.",
            "ar": "تنبيه ضباب كثيف على الطرق السريعة الشمالية حتى 09:00. خففوا السرعة واستخدموا أضواء الضباب وضاعفوا مسافة الأمان.",
        },
        "severity": "urgent",
        "active": True,
    },
    {
        "text": {
            "en": "Updated traffic fine schedule takes effect 1 August 2026. Review the new penalties in the Resource Center.",
            "ar": "يدخل جدول المخالفات المرورية المحدث حيز التنفيذ في 1 أغسطس 2026. راجعوا الغرامات الجديدة في مركز المراجع.",
        },
        "severity": "info",
        "active": True,
    },
]

NEWS = [
    {
        "nid": "n1",
        "category": "urgent",
        "date": "2026-07-08",
        "urgent": True,
        "title": {"en": "Weekend Road Closure: Coastal Highway Interchange", "ar": "إغلاق نهاية الأسبوع: تقاطع الطريق الساحلي"},
        "summary": {"en": "The Coastal Highway interchange closes Friday 23:00 to Sunday 05:00 for deck resurfacing. Signed diversions via Route 12 will be in place.",
                    "ar": "يُغلق تقاطع الطريق الساحلي من الجمعة 23:00 حتى الأحد 05:00 لأعمال إعادة رصف الجسر. ستتوفر تحويلات موضحة عبر الطريق 12."},
        "body": {"en": "Contractors will resurface the interchange deck and replace expansion joints. Emergency vehicle access is maintained at all times. Motorists should add 20 minutes to journey times or use public transport. The department thanks road users for their patience.",
                 "ar": "سيقوم المقاولون بإعادة رصف سطح التقاطع واستبدال وصلات التمدد. يبقى وصول مركبات الطوارئ متاحاً في جميع الأوقات. يُنصح السائقون بإضافة 20 دقيقة لرحلاتهم أو استخدام النقل العام. تشكر الإدارة مستخدمي الطريق على تعاونهم."},
    },
    {
        "nid": "n2",
        "category": "law",
        "date": "2026-07-01",
        "urgent": False,
        "title": {"en": "New Regulation: Mandatory Helmets for E-Scooter Riders", "ar": "تنظيم جديد: إلزامية الخوذة لمستخدمي الدراجات الكهربائية"},
        "summary": {"en": "From 1 August 2026, all e-scooter riders must wear certified helmets. Fines of 300 apply after a one-month awareness period.",
                    "ar": "اعتباراً من 1 أغسطس 2026، يجب على جميع مستخدمي الدراجات الكهربائية ارتداء خوذات معتمدة. تطبق غرامة قدرها 300 بعد فترة توعية لمدة شهر."},
        "body": {"en": "The regulation follows a 34% rise in micromobility injuries. Helmets must meet the national safety standard. Free helmet fitting events run at all community centres during July.",
                 "ar": "جاء هذا التنظيم بعد ارتفاع إصابات التنقل الخفيف بنسبة 34%. يجب أن تستوفي الخوذات المعيار الوطني للسلامة. تقام فعاليات تركيب خوذات مجانية في جميع المراكز المجتمعية خلال يوليو."},
    },
    {
        "nid": "n3",
        "category": "stats",
        "date": "2026-06-30",
        "urgent": False,
        "title": {"en": "June 2026 Road Safety Statistics Published", "ar": "نشر إحصاءات السلامة المرورية لشهر يونيو 2026"},
        "summary": {"en": "Serious collisions fell 12% year-on-year. School zone speeding incidents dropped to their lowest level since 2021.",
                    "ar": "انخفضت الحوادث الخطيرة بنسبة 12% مقارنة بالعام الماضي. وتراجعت مخالفات السرعة في المناطق المدرسية إلى أدنى مستوى منذ 2021."},
        "body": {"en": "June recorded 41 serious collisions against 47 in June 2025. Signal compliance reached 98.4%. Pedestrian incidents in school zones fell 19% following the Zero-Speed initiative. The full statistical bulletin is available in the Resource Center.",
                 "ar": "سجل شهر يونيو 41 حادثاً خطيراً مقابل 47 في يونيو 2025. وبلغت نسبة الالتزام بالإشارات 98.4%. وانخفضت حوادث المشاة في المناطق المدرسية بنسبة 19% بعد مبادرة صفر سرعة. النشرة الإحصائية الكاملة متاحة في مركز المراجع."},
    },
    {
        "nid": "n4",
        "category": "press",
        "date": "2026-06-18",
        "urgent": False,
        "title": {"en": "Department Launches Summer Child Seat Verification Tour", "ar": "الإدارة تطلق جولة صيفية لفحص مقاعد الأطفال"},
        "summary": {"en": "Certified technicians will offer free child seat checks at 22 locations across the region throughout July and August.",
                    "ar": "سيقدم فنيون معتمدون فحوصات مجانية لمقاعد الأطفال في 22 موقعاً across المنطقة خلال يوليو وأغسطس."},
        "body": {"en": "Four in ten child seats inspected last year were incorrectly fitted. The summer tour brings certified fitting stations to shopping centres, schools and community halls. No booking required.",
                 "ar": "أربعة من كل عشرة مقاعد أطفال تم فحصها العام الماضي كانت مركبة بشكل غير صحيح. تجلب الجولة الصيفية محطات تركيب معتمدة إلى المراكز التجارية والمدارس والقاعات المجتمعية. لا حاجة للحجز المسبق."},
    },
    {
        "nid": "n5",
        "category": "press",
        "date": "2026-06-05",
        "urgent": False,
        "title": {"en": "Night Visibility Campaign Distributes 50,000th Reflector", "ar": "حملة الرؤية الليلية توزع العاكس رقم 50,000"},
        "summary": {"en": "The pedestrian visibility campaign reached a milestone this week, with reflectors now standard issue in all primary schools.",
                    "ar": "بلغت حملة رؤية المشاة إنجازاً جديداً هذا الأسبوع، حيث أصبحت العواكس توزع بشكل قياسي في جميع المدارس الابتدائية."},
        "body": {"en": "Pedestrian fatalities after dark have fallen 27% since the campaign began. Reflective bands are available free at all department offices and participating fuel stations.",
                 "ar": "انخفضت وفيات المشاة بعد حلول الظلام بنسبة 27% منذ بدء الحملة. تتوفر الأشرطة العاكسة مجاناً في جميع مكاتب الإدارة ومحطات الوقود المشاركة."},
    },
]

QUIZ_QUESTIONS = [
    {
        "qid": "q1",
        "topic": {"en": "Speed Limits", "ar": "حدود السرعة"},
        "question": {"en": "What is the maximum speed limit in a marked school zone during school hours?",
                     "ar": "ما هو الحد الأقصى للسرعة في منطقة مدرسية محددة خلال ساعات الدوام المدرسي؟"},
        "options": [
            {"en": "50 km/h", "ar": "50 كم/س"},
            {"en": "40 km/h", "ar": "40 كم/س"},
            {"en": "30 km/h", "ar": "30 كم/س"},
            {"en": "60 km/h if the road is clear", "ar": "60 كم/س إذا كان الطريق خالياً"},
        ],
        "correct_index": 2,
        "explanation": {"en": "School zones carry a strict 30 km/h limit during arrival and dismissal hours. A child struck at 30 km/h has a 90% survival chance; at 50 km/h it falls below 20%.",
                        "ar": "تطبق المناطق المدرسية حداً صارماً قدره 30 كم/س خلال ساعات الحضور والانصراف. فرصة نجاة الطفل عند صدمه بسرعة 30 كم/س تبلغ 90%، بينما تنخفض إلى أقل من 20% عند 50 كم/س."},
    },
    {
        "qid": "q2",
        "topic": {"en": "Child Safety", "ar": "سلامة الأطفال"},
        "question": {"en": "Until what age must a child travel in an approved child restraint or booster seat?",
                     "ar": "حتى أي عمر يجب أن يستقل الطفل مقعد أمان معتمداً أو مقعداً رافعاً؟"},
        "options": [
            {"en": "2 years", "ar": "سنتان"},
            {"en": "4 years", "ar": "4 سنوات"},
            {"en": "10 years or 145 cm tall", "ar": "10 سنوات أو طول 145 سم"},
            {"en": "There is no legal requirement", "ar": "لا يوجد شرط قانوني"},
        ],
        "correct_index": 2,
        "explanation": {"en": "Children must use an approved restraint until age 10 or 145 cm, whichever comes first. Adult seatbelts are designed for bodies above that height and can injure smaller children in a crash.",
                        "ar": "يجب أن يستخدم الأطفال مقعد أمان معتمداً حتى سن 10 سنوات أو طول 145 سم، أيهما يتحقق أولاً. أحزمة الأمان للبالغين مصممة لأجسام أطول وقد تؤذي الأطفال الأصغر حجماً عند الحوادث."},
    },
    {
        "qid": "q3",
        "topic": {"en": "Pedestrian Priority", "ar": "أولوية المشاة"},
        "question": {"en": "A pedestrian steps onto a zebra crossing as you approach. What must you do?",
                     "ar": "عبَر أحد المشاة إلى ممر مشاة بينما تقترب أنت. ماذا يجب أن تفعل؟"},
        "options": [
            {"en": "Sound the horn and proceed carefully", "ar": "أطلق المنبه وتابع بحذر"},
            {"en": "Stop and give way until they finish crossing", "ar": "توقف وامنح الأولوية حتى ينهي العبور"},
            {"en": "Slow down but continue if there is a gap", "ar": "خفف السرعة وتابع إذا وُجدت مسافة"},
            {"en": "Flash your headlights to warn them", "ar": "ومض بالأضواء لتحذيرهم"},
        ],
        "correct_index": 1,
        "explanation": {"en": "Pedestrians on a marked crossing have absolute priority. Failing to stop carries a fine and penalty points, and is a leading cause of serious urban injuries.",
                        "ar": "للمشاة على ممر المشاة المحدد أولوية مطلقة. عدم التوقف يعرضك لغرامة ونقاط جزائية، وهو سبب رئيسي للإصابات الخطيرة داخل المدن."},
    },
    {
        "qid": "q4",
        "topic": {"en": "Roundabouts", "ar": "الدوارات"},
        "question": {"en": "When entering a roundabout, who has the right of way?",
                     "ar": "عند دخول الدوار، من له حق الأولوية؟"},
        "options": [
            {"en": "Vehicles entering from the main road", "ar": "المركبات القادمة من الطريق الرئيسي"},
            {"en": "Vehicles already circulating inside the roundabout", "ar": "المركبات الموجودة داخل الدوار"},
            {"en": "The largest vehicle", "ar": "المركبة الأكبر حجماً"},
            {"en": "Whoever arrives first", "ar": "من يصل أولاً"},
        ],
        "correct_index": 1,
        "explanation": {"en": "Always yield to traffic already circulating in the roundabout. Enter only when there is a safe gap, and signal your exit in good time.",
                        "ar": "امنح الأولوية دائماً للمركبات الموجودة داخل الدوار. ادخل فقط عند وجود مسافة آمنة، وأعط إشارة الخروج في الوقت المناسب."},
    },
    {
        "qid": "q5",
        "topic": {"en": "Distraction", "ar": "تشتت الانتباه"},
        "question": {"en": "Which statement about mobile phone use while driving is correct?",
                     "ar": "أي عبارة عن استخدام الهاتف الجوال أثناء القيادة صحيحة؟"},
        "options": [
            {"en": "Handheld use is allowed at red lights", "ar": "يُسمح بالاستخدام اليدوي عند الإشارة الحمراء"},
            {"en": "Texting is permitted under 40 km/h", "ar": "يُسمح بالرسائل النصية تحت 40 كم/س"},
            {"en": "Any handheld use is illegal, even when stationary in traffic", "ar": "أي استخدام يدوي مخالف للقانون حتى عند التوقف في الزحام"},
            {"en": "Only calls are banned; navigation apps are exempt", "ar": "المكالمات فقط ممنوعة وتطبيقات الملاحة مستثناة"},
        ],
        "correct_index": 2,
        "explanation": {"en": "Handheld phone use is prohibited whenever you are in control of the vehicle, including at signals. Reading a message at 50 km/h means driving blind for the length of a basketball court.",
                        "ar": "يُحظر الاستخدام اليدوي للهاتف كلما كنت متحكماً في المركبة، بما في ذلك عند الإشارات. قراءة رسالة بسرعة 50 كم/س تعني القيادة معصوب العينين لمسافة ملعب كرة سلة."},
    },
    {
        "qid": "q6",
        "topic": {"en": "Occupant Safety", "ar": "سلامة الركاب"},
        "question": {"en": "Who is responsible for ensuring rear-seat passengers wear seatbelts?",
                     "ar": "من المسؤول عن التأكد من ارتداء ركاب المقاعد الخلفية لأحزمة الأمان؟"},
        "options": [
            {"en": "Only the passengers themselves", "ar": "الركاب أنفسهم فقط"},
            {"en": "The driver of the vehicle", "ar": "سائق المركبة"},
            {"en": "No one; rear belts are optional", "ar": "لا أحد؛ الأحزمة الخلفية اختيارية"},
            {"en": "Only on highways", "ar": "فقط على الطرق السريعة"},
        ],
        "correct_index": 1,
        "explanation": {"en": "The driver is legally responsible for every occupant being restrained. An unbelted rear passenger becomes a projectile in a crash, endangering everyone in the vehicle.",
                        "ar": "السائق مسؤول قانوناً عن تقيد جميع الركاب بالأحزمة. الراكب غير المقيد في الخلف يتحول عند الحادث إلى جسم مقذوف يهدد جميع من في المركبة."},
    },
    {
        "qid": "q7",
        "topic": {"en": "Signals", "ar": "الإشارات"},
        "question": {"en": "A traffic light turns amber as you approach. What does it mean?",
                     "ar": "تحولت الإشارة إلى اللون الكهرماني بينما تقترب. ماذا يعني ذلك؟"},
        "options": [
            {"en": "Accelerate to clear the junction", "ar": "أسرع لعبور التقاطع"},
            {"en": "Stop, unless stopping would be unsafe", "ar": "توقف، ما لم يكن التوقف غير آمن"},
            {"en": "Amber has the same meaning as green", "ar": "الكهرماني مثل الأخضر تماماً"},
            {"en": "Only buses must stop", "ar": "الحافلات فقط يجب أن تتوقف"},
        ],
        "correct_index": 1,
        "explanation": {"en": "Amber means stop unless you are so close that braking would cause danger. Entering on a late amber is treated the same as running a red light.",
                        "ar": "اللون الكهرماني يعني التوقف إلا إذا كنت قريباً جداً بحيث يسبب التوقف خطراً. العبور مع الكهرماني المتأخر يعامل كتجاوز الإشارة الحمراء."},
    },
    {
        "qid": "q8",
        "topic": {"en": "Following Distance", "ar": "مسافة التتبع"},
        "question": {"en": "What is the minimum safe following distance in dry conditions?",
                     "ar": "ما هي المسافة الآمنة الدنيا للتتبع في الظروف الجافة؟"},
        "options": [
            {"en": "One car length", "ar": "طول سيارة واحدة"},
            {"en": "The two-second rule", "ar": "قاعدة الثانيتين"},
            {"en": "Half a second", "ar": "نصف ثانية"},
            {"en": "Distance does not matter with ABS brakes", "ar": "المسافة غير مهمة مع فرامل ABS"},
        ],
        "correct_index": 1,
        "explanation": {"en": "Keep at least two seconds behind the vehicle ahead — four in rain, ten on ice. At 100 km/h you travel 55 metres in two seconds.",
                        "ar": "حافظ على ثانيتين على الأقل خلف المركبة الأمامية، وأربع في المطر وعشر على الجليد. بسرعة 100 كم/س تقطع 55 متراً في ثانيتين."},
    },
]

RESOURCES = [
    {
        "rid": "driver-handbook-2026",
        "category": {"en": "Driver Manuals", "ar": "أدلة السائقين"},
        "title": {"en": "Official Driver Handbook 2026", "ar": "دليل السائق الرسمي 2026"},
        "description": {"en": "The complete rules of the road: signs, signals, right of way, licensing and vehicle standards.",
                        "ar": "قواعد الطريق الكاملة: اللافتات والإشارات وحق الأولوية والترخيص ومعايير المركبات."},
        "updated": "2026-01-15",
        "pages": 84,
        "body_en": "This handbook sets out the rules every driver must know. Chapter 1 covers road signs and markings. Chapter 2 explains right of way at junctions, roundabouts and pedestrian crossings. Chapter 3 details speed limits by road class. Chapter 4 covers licensing, vehicle registration and periodic inspection. Chapter 5 explains penalties, fines and the points system. Keep this handbook in your vehicle and review it whenever regulations change.",
    },
    {
        "rid": "child-seat-guide",
        "category": {"en": "Child Safety", "ar": "سلامة الأطفال"},
        "title": {"en": "Child Seat Installation & Fitting Guide", "ar": "دليل تركيب وتثبيت مقاعد الأطفال"},
        "description": {"en": "Step-by-step fitting instructions for rear-facing, forward-facing and booster seats, with the 2026 legal requirements.",
                        "ar": "تعليمات تركيب خطوة بخطوة للمقاعد المواجهة للخلف والأمام والمقاعد الرافعة، مع المتطلبات القانونية لعام 2026."},
        "updated": "2026-03-02",
        "pages": 26,
        "body_en": "Children must travel in an approved restraint until age 10 or 145 cm. Rear-facing seats are required for infants up to 15 months. Check that the harness lies flat, the seat moves no more than 2.5 cm at the belt path, and the chest clip sits at armpit level. Never fit a rear-facing seat in front of an active airbag. Free verification is available at all department fitting stations.",
    },
    {
        "rid": "fines-schedule-2026",
        "category": {"en": "Regulations", "ar": "الأنظمة"},
        "title": {"en": "Traffic Fines & Penalty Schedule (August 2026)", "ar": "جدول المخالفات والغرامات المرورية (أغسطس 2026)"},
        "description": {"en": "Full schedule of fines, penalty points and vehicle impoundment rules effective 1 August 2026.",
                        "ar": "الجدول الكامل للغرامات والنقاط الجزائية وقواعد حجز المركبات اعتباراً من 1 أغسطس 2026."},
        "updated": "2026-06-20",
        "pages": 12,
        "body_en": "Effective 1 August 2026: speeding in school zones carries a fine of 900 and 6 points. Handheld phone use carries 500 and 4 points. Failure to stop for a pedestrian on a crossing carries 600 and 4 points. Not wearing a seatbelt carries 300 and 2 points per unrestrained occupant. Accumulating 24 points in 12 months results in licence suspension. Fines double in active school and work zones.",
    },
    {
        "rid": "school-transport-protocol",
        "category": {"en": "School Safety", "ar": "السلامة المدرسية"},
        "title": {"en": "School Transport Safety Protocol", "ar": "بروتوكول سلامة النقل المدرسي"},
        "description": {"en": "Mandatory safety standards for school buses, drivers, escorts and pick-up/drop-off zone management.",
                        "ar": "معايير السلامة الإلزامية للحافلات المدرسية والسائقين والمرافقين وإدارة مناطق الصعود والنزول."},
        "updated": "2026-02-10",
        "pages": 18,
        "body_en": "All school buses must display stop arms and flashing amber lights. Drivers must hold a category D licence with a school transport endorsement. Every bus requires a trained escort for pupils under 12. Vehicles in both directions must stop when the stop arm is deployed. Bus operators must conduct monthly brake and door safety checks and file reports with the department.",
    },
    {
        "rid": "pedestrian-cyclist-guide",
        "category": {"en": "Guides", "ar": "إرشادات"},
        "title": {"en": "Pedestrian & Cyclist Safety Guide", "ar": "دليل سلامة المشاة وراكبي الدراجات"},
        "description": {"en": "Visibility, crossing rules, helmet standards and safe route planning for people walking and cycling.",
                        "ar": "الرؤية وقواعد العبور ومعايير الخوذات وتخطيط المسارات الآمنة للمشاة وراكبي الدراجات."},
        "updated": "2026-04-08",
        "pages": 20,
        "body_en": "Wear reflective material after dark: a pedestrian with a reflector is visible at 150 metres, without one at only 30 metres. Cross only at marked crossings or signalised junctions. Cyclists must use front white and rear red lights at night, ride with traffic, and wear a certified helmet. Plan routes using protected lanes shown on the department cycle map.",
    },
]
